language: c

before_install:
  - curl http://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2 | tar xj
  - mkdir -p $HOME/bin
  - mv arduino-cli $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin

install:
  #arduino boards
  - arduino-cli core update-index
  - arduino-cli core install arduino:avr
  #arduino libraries
  - arduino-cli lib update-index
  - arduino-cli lib install "MCCI LoRaWAN LMIC library"
 # - arduino-cli lib install "Low-Power"
 # - arduino-cli lib install "I2C-Sensor-Lib iLib"

script:
  - arduino-cli compile -b arduino:avr:pro ultimate_ttn_mapper.ino
